import './globals.scss';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: { default: 'cozyshop | milad ', template: '%s | milad' },
  description: 'Generated by creat next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="nav">
          <Link className="link1" href="/">
            home
          </Link>{' '}
          <Link className="link2" href="/categorie">
            products
          </Link>
          <Link className="link3" href="/about">
            about
          </Link>
          <Link className="link4" href="/contact">
            contact
          </Link>
          <Link href="/cart">cart</Link>
        </nav>

        {children}
      </body>
    </html>
  );
}
